from __future__ import annotations

from datetime import date, datetime, timezone
from pathlib import Path
import argparse
import sys
from typing import Iterable

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.validate_holidays import load_holidays, validate_holidays

CALENDAR_DOMAIN = "calendar.local"
DEFAULT_YEARS = 5
DATA_FILE = Path(__file__).resolve().parents[1] / "data" / "holidays.yaml"
DIST_DIR = Path(__file__).resolve().parents[1] / "dist"
PRODID = "-//Other Holidays ICS//ZH//EN"
CALENDAR_METADATA = {
    "all.ics": ("其他节日（全部）", "中国大陆法定节假日之外的补充型节日订阅。"),
    "environment.ics": ("其他节日（环保与社会议题）", "环保、健康、包容与社会主题相关节日订阅。"),
    "culture-reading.ics": ("其他节日（文化与阅读）", "阅读、语言、教育、博物馆与文化主题节日订阅。"),
    "festivals.ics": ("其他节日（常见节庆）", "大众熟知的国际文化节庆订阅。"),
}
CATEGORY_TO_FILE = {
    "environment": "environment.ics",
    "culture-reading": "culture-reading.ics",
    "festivals": "festivals.ics",
}


def normalize_base_url(base_url: str) -> str:
    return base_url.rstrip("/")


def build_uid(holiday_id: str, year: int, domain: str) -> str:
    return f"{holiday_id}-{year}@{domain}"


def expand_holiday(holiday: dict, year: int, domain: str) -> dict:
    start_date = date(year, int(holiday["month"]), int(holiday["day"]))
    end_date = start_date.fromordinal(start_date.toordinal() + 1)
    return {
        "uid": build_uid(holiday["id"], year, domain),
        "summary": holiday["name_zh"],
        "description": holiday.get("description", ""),
        "start": start_date.strftime("%Y%m%d"),
        "end": end_date.strftime("%Y%m%d"),
        "status": "CONFIRMED",
        "transp": "TRANSPARENT",
        "category": holiday["categories"][0],
        "holiday_id": holiday["id"],
    }


def escape_ics_text(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace(";", "\\;")
        .replace(",", "\\,")
        .replace("\n", "\\n")
    )


def render_event(event: dict, dtstamp: str) -> list[str]:
    lines = [
        "BEGIN:VEVENT",
        f"UID:{event['uid']}",
        f"DTSTAMP:{dtstamp}",
        f"SUMMARY:{escape_ics_text(event['summary'])}",
    ]
    if event["description"]:
        lines.append(f"DESCRIPTION:{escape_ics_text(event['description'])}")
    lines.extend(
        [
            f"DTSTART;VALUE=DATE:{event['start']}",
            f"DTEND;VALUE=DATE:{event['end']}",
            f"STATUS:{event['status']}",
            f"TRANSP:{event['transp']}",
            "END:VEVENT",
        ]
    )
    return lines


def render_calendar(filename: str, events: list[dict], dtstamp: str) -> str:
    cal_name, cal_desc = CALENDAR_METADATA[filename]
    lines = [
        "BEGIN:VCALENDAR",
        f"PRODID:{PRODID}",
        "VERSION:2.0",
        "CALSCALE:GREGORIAN",
        f"X-WR-CALNAME:{escape_ics_text(cal_name)}",
        f"X-WR-CALDESC:{escape_ics_text(cal_desc)}",
    ]
    for event in sorted(events, key=lambda item: (item["start"], item["holiday_id"])):
        lines.extend(render_event(event, dtstamp))
    lines.append("END:VCALENDAR")
    return "\n".join(lines) + "\n"


def render_index(base_url: str) -> str:
    normalized = normalize_base_url(base_url)
    cards: list[str] = []
    for filename, (name, desc) in CALENDAR_METADATA.items():
        href = f"{normalized}/{filename}"
        primary_cta = "订阅全部节日" if filename == "all.ics" else "订阅这个分组"
        cards.extend(
            [
                '          <article class="subscription-card">',
                f'            <p class="eyebrow">{filename}</p>',
                f'            <h3>{name}</h3>',
                f'            <p class="card-description">{desc}</p>',
                '            <div class="card-actions">',
                f'              <a class="button button-primary" href="{href}">{primary_cta}</a>',
                f'              <a class="button button-secondary" href="{href}">复制 / 打开链接</a>',
                '            </div>',
                f'            <p class="subscription-url">{href}</p>',
                '          </article>',
            ]
        )

    lines = [
        "<!doctype html>",
        '<html lang="zh-CN">',
        "<head>",
        '  <meta charset="utf-8">',
        '  <meta name="viewport" content="width=device-width, initial-scale=1">',
        '  <meta name="color-scheme" content="dark">',
        '  <meta name="description" content="中国大陆法定节假日之外的补充型节日订阅，支持 Apple Calendar 等支持 ICS 的日历客户端。">',
        '  <link rel="preconnect" href="https://fonts.googleapis.com">',
        '  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
        '  <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500;600;700&family=Manrope:wght@400;500;600;700&display=swap" rel="stylesheet">',
        "  <title>其他节日 ICS 订阅</title>",
        "  <style>",
        "    :root {",
        "      --bg: #1f171d;",
        "      --bg-soft: rgba(46, 32, 40, 0.72);",
        "      --panel: rgba(29, 22, 28, 0.52);",
        "      --panel-border: rgba(231, 221, 216, 0.12);",
        "      --text: #e7ddd8;",
        "      --muted: rgba(231, 221, 216, 0.72);",
        "      --accent: #6f8f8b;",
        "      --accent-strong: #b4c5bb;",
        "      --glow: rgba(111, 143, 139, 0.32);",
        "      --lavender: rgba(184, 166, 184, 0.55);",
        "      --pale-lilac: rgba(207, 198, 207, 0.7);",
        "      --sage: rgba(124, 154, 116, 0.34);",
        "      --moss: rgba(77, 107, 69, 0.30);",
        "      --warm: rgba(175, 143, 124, 0.14);",
        "      --shadow: 0 30px 80px rgba(0, 0, 0, 0.45);",
        "      --radius: 28px;",
        "      font-family: 'Manrope', Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;",
        "    }",
        "    * { box-sizing: border-box; }",
        "    html, body { height: 100%; scroll-behavior: smooth; }",
        "    body {",
        "      margin: 0;",
        "      color: var(--text);",
        "      background:",
        "        radial-gradient(circle at 20% 20%, rgba(77, 107, 69, 0.28), transparent 30%),",
        "        radial-gradient(circle at 78% 18%, rgba(184, 166, 184, 0.20), transparent 26%),",
        "        radial-gradient(circle at 52% 75%, rgba(207, 198, 207, 0.10), transparent 24%),",
        "        linear-gradient(180deg, #34262f 0%, #241b23 42%, #1a1318 100%);",
        "      overflow-x: hidden;",
        "    }",
        "    body::before {",
        "      content: '';",
        "      position: fixed;",
        "      inset: 0;",
        "      background: linear-gradient(180deg, rgba(9, 8, 9, 0.08) 0%, rgba(20, 14, 18, 0.36) 100%);",
        "      pointer-events: none;",
        "      z-index: 1;",
        "    }",
        "    #three-scene {",
        "      position: fixed;",
        "      inset: 0;",
        "      width: 100%;",
        "      height: 100%;",
        "      z-index: 0;",
        "      pointer-events: none;",
        "      opacity: 0.98;",
        "      mix-blend-mode: screen;",
        "    }",
        "    .orb {",
        "      position: fixed;",
        "      border-radius: 50%;",
        "      filter: blur(60px);",
        "      pointer-events: none;",
        "      z-index: 0;",
        "      opacity: 0.45;",
        "    }",
        "    .orb-left {",
        "      width: 24rem; height: 24rem; left: -6rem; top: 12vh;",
        "      background: rgba(77, 107, 69, 0.26);",
        "      animation: drift 18s ease-in-out infinite alternate;",
        "    }",
        "    .orb-right {",
        "      width: 20rem; height: 20rem; right: -4rem; top: 8vh;",
        "      background: rgba(184, 166, 184, 0.22);",
        "      animation: drift 22s ease-in-out infinite alternate-reverse;",
        "    }",
        "    .page-shell { position: relative; z-index: 2; min-height: 100vh; }",
        "    .chrome-nav {",
        "      position: fixed; inset: 0; z-index: 3; pointer-events: none;",
        "      padding: 1.4rem 1.4rem 1.8rem;",
        "    }",
        "    .chrome-nav a, .chrome-nav button { pointer-events: auto; }",
        "    .chrome-top { display: flex; justify-content: space-between; align-items: flex-start; gap: 1rem; }",
        "    .menu-button {",
        "      background: transparent; border: 0; color: var(--text); display: inline-grid; gap: 0.45rem; padding: 0; cursor: pointer; text-align: left;",
        "    }",
        "    .menu-lines { display: grid; gap: 0.3rem; }",
        "    .menu-lines span { display: block; width: 2.3rem; height: 1px; background: rgba(231,221,216,0.72); }",
        "    .menu-button em { font-style: normal; font-size: 0.78rem; letter-spacing: 0.16em; text-transform: uppercase; color: rgba(231,221,216,0.78); }",
        "    .brand-mark { text-align: right; max-width: 18rem; text-decoration: none; color: inherit; }",
        "    .brand-mark strong { display: block; font-family: 'Cormorant Garamond', Georgia, serif; font-size: clamp(1.8rem, 3vw, 2.8rem); line-height: 0.9; font-weight: 600; }",
        "    .brand-mark span { display: block; margin-top: 0.35rem; font-size: 0.72rem; letter-spacing: 0.18em; text-transform: uppercase; color: rgba(231,221,216,0.62); }",
        "    .chrome-sides { position: absolute; inset: 50% 0 auto; transform: translateY(-50%); display: flex; justify-content: space-between; padding: 0 1rem; }",
        "    .side-arrow {",
        "      width: 2.8rem; height: 2.8rem; border-radius: 999px; border: 1px solid rgba(231,221,216,0.16); display: inline-flex; align-items: center; justify-content: center; color: rgba(231,221,216,0.82); text-decoration: none; background: rgba(29,22,28,0.24); backdrop-filter: blur(10px);",
        "    }",
        "    .side-arrow span { font-size: 1.1rem; transform: translateY(-1px); }",
        "    .chrome-bottom { position: absolute; inset: auto 1.4rem 0; display: flex; justify-content: flex-end; padding-bottom: 1rem; }",
        "    .footer-mini-nav { display: inline-flex; gap: 1rem; align-items: center; }",
        "    .footer-mini-nav a { color: rgba(231,221,216,0.72); text-decoration: none; font-size: 0.76rem; letter-spacing: 0.18em; text-transform: uppercase; }",
        "    .footer-mini-nav a:hover, .brand-mark:hover strong, .menu-button:hover em { color: #ffffff; }",
        "    .enter-stage {",
        "      min-height: 100vh;",
        "      display: grid;",
        "      place-items: center;",
        "      padding: 4rem clamp(1.25rem, 3vw, 3rem) 2rem;",
        "      text-align: center;",
        "    }",
        "    .enter-stage-inner {",
        "      width: min(760px, 100%);",
        "      display: grid;",
        "      justify-items: center;",
        "      gap: 1.15rem;",
        "      transition: transform 280ms ease;",
        "    }",
        "    .portal-ring {",
        "      width: clamp(8rem, 16vw, 10.5rem);",
        "      aspect-ratio: 1;",
        "      border-radius: 50%;",
        "      border: 1px solid rgba(231, 221, 216, 0.26);",
        "      box-shadow: 0 0 0 1px rgba(255,255,255,0.05) inset, 0 0 36px rgba(111, 143, 139, 0.18), 0 0 88px rgba(184, 166, 184, 0.14);",
        "      position: relative;",
        "      background: radial-gradient(circle, rgba(207, 198, 207, 0.10) 0%, rgba(124, 154, 116, 0.05) 45%, transparent 72%);",
        "      backdrop-filter: blur(12px);",
        "      animation: pulse-ring 8s ease-in-out infinite;",
        "    }",
        "    .portal-ring::before, .portal-ring::after {",
        "      content: ''; position: absolute; inset: 12%; border-radius: 50%; border: 1px solid rgba(255,255,255,0.09);",
        "    }",
        "    .portal-ring::after { inset: 28%; border-color: rgba(111, 143, 139, 0.36); }",
        "    .enter-overline {",
        "      margin: 0; letter-spacing: 0.42em; text-transform: uppercase; color: var(--accent-strong); font-size: 0.75rem;",
        "    }",
        "    .enter-title {",
        "      margin: 0;",
        "      font-family: 'Cormorant Garamond', 'Iowan Old Style', 'Palatino Linotype', 'Book Antiqua', Georgia, serif;",
        "      font-size: clamp(3.4rem, 7.6vw, 6.8rem);",
        "      line-height: 0.95;",
        "      letter-spacing: -0.045em;",
        "      max-width: 9ch;",
        "      text-wrap: balance;",
        "      text-shadow: 0 0 24px rgba(231, 221, 216, 0.10);",
        "      animation: float-title 11s ease-in-out infinite;",
        "    }",
        "    .enter-description {",
        "      margin: 0; max-width: 38rem; color: var(--muted); line-height: 1.95; font-size: clamp(1rem, 1.7vw, 1.14rem);",
        "    }",
        "    .enter-button {",
        "      width: clamp(9rem, 16vw, 10.5rem); height: clamp(9rem, 16vw, 10.5rem); border-radius: 50%;",
        "      background: radial-gradient(circle at 35% 30%, #d9d6d1 0%, #8ba39e 42%, #5f7976 100%);",
        "      color: #1c171b; font-size: 1.02rem; letter-spacing: 0.18em; text-transform: uppercase;",
        "      box-shadow: 0 20px 65px rgba(111, 143, 139, 0.34), 0 0 32px rgba(207, 198, 207, 0.18);",
        "      position: relative;",
        "      animation: pulse-enter 3.6s ease-in-out infinite;",
        "    }",
        "    .enter-button::after {",
        "      content: ''; position: absolute; left: 50%; top: calc(100% + 0.6rem); width: 1px; height: 3.5rem; background: linear-gradient(180deg, rgba(205,223,255,0.7), rgba(205,223,255,0)); transform: translateX(-50%);",
        "    }",
        "    .enter-note {",
        "      margin: 0.4rem 0 0; font-size: 0.9rem; letter-spacing: 0.18em; text-transform: uppercase; color: rgba(244, 239, 232, 0.5);",
        "    }",
        "    .hero {",
        "      min-height: 100vh;",
        "      display: grid;",
        "      align-items: center;",
        "      padding: 2rem clamp(1.25rem, 3vw, 3rem) 4rem;",
        "    }",
        "    .hero-secondary { min-height: auto; padding-top: 0; }",
        "    .hero-panel {",
        "      max-width: 1180px;",
        "      margin: 0 auto;",
        "      width: 100%;",
        "      display: grid;",
        "      grid-template-columns: minmax(0, 1.15fr) minmax(320px, 0.95fr);",
        "      gap: clamp(1.5rem, 3vw, 3rem);",
        "      align-items: center;",
        "    }",
        "    .intro {",
        "      padding: clamp(1rem, 2vw, 2rem);",
        "    }",
        "    .kicker {",
        "      letter-spacing: 0.34em;",
        "      text-transform: uppercase;",
        "      color: var(--accent-strong);",
        "      font-size: 0.78rem;",
        "      margin-bottom: 1.5rem;",
        "    }",
        "    h1 {",
        "      margin: 0;",
        "      font-family: 'Iowan Old Style', 'Palatino Linotype', 'Book Antiqua', Georgia, serif;",
        "      font-size: clamp(3.2rem, 7vw, 6.4rem);",
        "      line-height: 0.96;",
        "      letter-spacing: -0.04em;",
        "      max-width: 11ch;",
        "      text-wrap: balance;",
        "    }",
        "    .lead {",
        "      margin: 1.5rem 0 0;",
        "      max-width: 36rem;",
        "      font-size: clamp(1.02rem, 1.7vw, 1.16rem);",
        "      line-height: 1.85;",
        "      color: var(--muted);",
        "    }",
        "    .meta-row {",
        "      margin-top: 2rem;",
        "      display: flex;",
        "      flex-wrap: wrap;",
        "      gap: 0.75rem;",
        "    }",
        "    .meta-pill {",
        "      display: inline-flex; align-items: center; gap: 0.55rem;",
        "      padding: 0.75rem 1rem;",
        "      border-radius: 999px;",
        "      background: rgba(255,255,255,0.06);",
        "      border: 1px solid rgba(255,255,255,0.10);",
        "      backdrop-filter: blur(14px);",
        "      color: var(--text);",
        "      font-size: 0.94rem;",
        "    }",
        "    .meta-dot { width: 0.5rem; height: 0.5rem; border-radius: 50%; background: var(--accent); box-shadow: 0 0 14px var(--glow); }",
        "    .hero-actions {",
        "      margin-top: 2rem;",
        "      display: flex;",
        "      gap: 0.9rem;",
        "      flex-wrap: wrap;",
        "      animation: rise-in 900ms ease both;",
        "    }",
        "    .section-fade { opacity: 0; transform: translateY(26px); transition: opacity 800ms ease, transform 800ms ease; }",
        "    .section-fade.is-visible { opacity: 1; transform: translateY(0); }",
        "    .button {",
        "      display: inline-flex;",
        "      align-items: center;",
        "      justify-content: center;",
        "      min-height: 3.2rem;",
        "      padding: 0.95rem 1.35rem;",
        "      border-radius: 999px;",
        "      border: 1px solid transparent;",
        "      text-decoration: none;",
        "      font-weight: 600;",
        "      transition: transform 160ms ease, background 160ms ease, border-color 160ms ease, box-shadow 160ms ease;",
        "    }",
        "    .button:hover { transform: translateY(-1px); }",
        "    .button-primary {",
        "      color: #1d171b;",
        "      background: linear-gradient(135deg, #dfd9d5 0%, #8ba39e 100%);",
        "      box-shadow: 0 16px 38px rgba(111, 143, 139, 0.28);",
        "    }",
        "    .button-secondary {",
        "      color: var(--text);",
        "      border-color: rgba(255,255,255,0.14);",
        "      background: rgba(255,255,255,0.04);",
        "      backdrop-filter: blur(14px);",
        "    }",
        "    .hero-note {",
        "      margin-top: 1rem;",
        "      font-size: 0.92rem;",
        "      color: rgba(244, 239, 232, 0.64);",
        "      letter-spacing: 0.06em;",
        "    }",
        "    .hero-card {",
        "      position: relative;",
        "      padding: clamp(1.4rem, 2vw, 2rem);",
        "      background: linear-gradient(180deg, rgba(38, 28, 34, 0.64), rgba(20, 16, 20, 0.58));",
        "      border: 1px solid var(--panel-border);",
        "      border-radius: var(--radius);",
        "      box-shadow: var(--shadow);",
        "      backdrop-filter: blur(20px);",
        "      overflow: hidden;",
        "      isolation: isolate;",
        "    }",
        "    .hero-card::before {",
        "      content: '';",
        "      position: absolute;",
        "      inset: auto -20% 65% 45%;",
        "      height: 10rem;",
        "      background: linear-gradient(90deg, rgba(111, 143, 139, 0), rgba(111, 143, 139, 0.16), rgba(184, 166, 184, 0));",
        "      transform: rotate(-18deg);",
        "      z-index: -1;",
        "    }",
        "    .section-label {",
        "      font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.26em; color: var(--accent-strong); margin-bottom: 1rem;",
        "    }",
        "    .section-title { margin: 0 0 0.8rem; font-size: 1.35rem; }",
        "    .section-copy { margin: 0; color: var(--muted); line-height: 1.8; }",
        "    .stats {",
        "      margin-top: 1.5rem;",
        "      display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 0.9rem;",
        "    }",
        "    .stat {",
        "      padding: 1rem; border-radius: 20px; background: rgba(255,255,255,0.05); border: 1px solid rgba(255,255,255,0.08);",
        "    }",
        "    .stat strong { display: block; font-size: 1.4rem; margin-bottom: 0.3rem; }",
        "    .stat span { font-size: 0.88rem; color: var(--muted); }",
        "    .subscriptions { padding: 0  clamp(1.25rem, 3vw, 3rem) 5rem; }",
        "    .subscriptions-inner { max-width: 1180px; margin: 0 auto; }",
        "    .subscriptions-header { margin-bottom: 1.5rem; }",
        "    .subscriptions-header h2 { margin: 0; font-size: clamp(1.8rem, 3vw, 2.7rem); }",
        "    .subscriptions-header p { margin: 0.9rem 0 0; color: var(--muted); max-width: 44rem; line-height: 1.8; }",
        "    .subscription-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 1rem; }",
        "    .subscription-card {",
        "      position: relative;",
        "      padding: 1.4rem;",
        "      background: linear-gradient(180deg, rgba(35, 27, 32, 0.74), rgba(18, 15, 18, 0.68));",
        "      border-radius: 24px;",
        "      border: 1px solid rgba(255,255,255,0.1);",
        "      box-shadow: var(--shadow);",
        "      backdrop-filter: blur(18px);",
        "      overflow: hidden;",
        "    }",
        "    .subscription-card::after {",
        "      content: ''; position: absolute; inset: 0; background: linear-gradient(135deg, rgba(111,143,139,0.10), rgba(255,255,255,0) 45%, rgba(184,166,184,0.08)); pointer-events: none;",
        "    }",
        "    .eyebrow { margin: 0 0 0.8rem; color: rgba(244, 239, 232, 0.5); font-size: 0.78rem; letter-spacing: 0.18em; text-transform: uppercase; }",
        "    .subscription-card h3 { margin: 0; font-size: 1.25rem; }",
        "    .card-description { margin: 0.8rem 0 1rem; color: var(--muted); line-height: 1.75; min-height: 4.8em; }",
        "    .card-actions { display: flex; gap: 0.75rem; flex-wrap: wrap; }",
        "    .subscription-url { margin: 1rem 0 0; color: rgba(244, 239, 232, 0.56); font-size: 0.82rem; line-height: 1.65; word-break: break-all; }",
        "    .footer-note { padding: 0 clamp(1.25rem, 3vw, 3rem) 4rem; }",
        "    .footer-note-inner { max-width: 1180px; margin: 0 auto; color: rgba(244, 239, 232, 0.56); font-size: 0.92rem; line-height: 1.7; }",
        "    @keyframes drift {",
        "      from { transform: translate3d(0, 0, 0) scale(1); }",
        "      to { transform: translate3d(2rem, -1.5rem, 0) scale(1.06); }",
        "    }",
        "    @keyframes pulse-ring {",
        "      0%, 100% { transform: scale(1); opacity: 0.9; }",
        "      50% { transform: scale(1.035); opacity: 1; }",
        "    }",
        "    @keyframes pulse-enter {",
        "      0%, 100% { transform: translateY(0) scale(1); }",
        "      50% { transform: translateY(-2px) scale(1.025); }",
        "    }",
        "    @keyframes float-title {",
        "      0%, 100% { transform: translateY(0); }",
        "      50% { transform: translateY(-8px); }",
        "    }",
        "    @keyframes rise-in {",
        "      from { opacity: 0; transform: translateY(16px); }",
        "      to { opacity: 1; transform: translateY(0); }",
        "    }",
        "    @media (max-width: 960px) {",
        "      .chrome-sides { display: none; }",
        "      .hero-panel, .subscription-grid { grid-template-columns: 1fr; }",
        "      .stats { grid-template-columns: 1fr 1fr; }",
        "      h1 { max-width: 12ch; }",
        "    }",
        "    @media (max-width: 640px) {",
        "      .chrome-nav { padding: 1rem 1rem 1.2rem; }",
        "      .brand-mark strong { font-size: 1.6rem; }",
        "      .hero { padding-top: 5rem; }",
        "      .stats { grid-template-columns: 1fr; }",
        "      .hero-actions, .card-actions { flex-direction: column; }",
        "      .button { width: 100%; }",
        "    }",
        "  </style>",
        "</head>",
        "<body>",
        '  <canvas id="three-scene" aria-hidden="true"></canvas>',
        '  <div class="orb orb-left" aria-hidden="true"></div>',
        '  <div class="orb orb-right" aria-hidden="true"></div>',
        '  <div class="chrome-nav" aria-hidden="false">',
        '    <div class="chrome-top">',
        '      <button class="menu-button" type="button" aria-label="Open menu">',
        '        <span class="menu-lines"><span></span><span></span><span></span></span>',
        '        <em>Menu</em>',
        '      </button>',
        '      <a class="brand-mark" href="#hero-content">',
        '        <strong>Other Holidays Archive</strong>',
        '        <span>curated observances · immersive entrance</span>',
        '      </a>',
        '    </div>',
        '    <div class="chrome-sides">',
        '      <a class="side-arrow" href="#hero-content" aria-label="Enter main content"><span>‹</span></a>',
        '      <a class="side-arrow" href="#subscriptions" aria-label="Jump to subscriptions"><span>›</span></a>',
        '    </div>',
        '    <div class="chrome-bottom">',
        '      <nav class="footer-mini-nav" aria-label="Footer mini navigation">',
        '        <a href="#hero-content">Archive</a>',
        '        <a href="#subscriptions">Collections</a>',
        '        <a href="#about">ABOUT</a>',
        '      </nav>',
        '    </div>',
        '  </div>',
        '  <div class="page-shell">',
        '    <main>',
        '      <section class="enter-stage">',
        '        <div class="enter-stage-inner">',
        '          <div class="portal-ring" aria-hidden="true"></div>',
        '          <p class="enter-overline">holiday observance archive</p>',
        '          <h1 class="enter-title">将国际节日放进你的日历星图</h1>',
        '          <p class="enter-description">这是一个只收录“其他节日”的静态 ICS 订阅：不重复中国大陆法定节假日，只保留地球日、世界读书日、圣诞节以及阅读、环保、文化相关的重要日期。现在它先以一个更安静的门厅迎接你，再把订阅入口缓慢展开。</p>',
        '          <a class="button enter-button" href="#hero-content">进入节日宇宙</a>',
        '          <p class="enter-note">向下进入 · curated observances</p>',
        '        </div>',
        '      </section>',
        '      <section class="hero hero-secondary section-fade" id="hero-content">',
        '        <div class="hero-panel">',
        '          <div class="intro">',
        '            <p class="kicker">holiday ics subscription</p>',
        '            <h1>将国际节日放进你的日历星图</h1>',
        '            <p class="lead">这是一个只收录“其他节日”的静态 ICS 订阅：不重复中国大陆法定节假日，只保留地球日、世界读书日、圣诞节以及阅读、环保、文化相关的重要日期。</p>',
        '            <div class="meta-row">',
        '              <span class="meta-pill"><span class="meta-dot"></span>Apple Calendar 已验证</span>',
        '              <span class="meta-pill"><span class="meta-dot"></span>27 个固定公历节日</span>',
        '              <span class="meta-pill"><span class="meta-dot"></span>支持长期 ICS 订阅</span>',
        '            </div>',
        '            <div class="hero-actions">',
        f'              <a class="button button-primary" href="{normalized}/all.ics">订阅全部节日</a>',
        '              <a class="button button-secondary" href="#subscriptions">查看分组订阅</a>',
        '            </div>',
        '            <p class="hero-note">Three.js 真 3D 粒子背景 + 更接近展览站门厅感的首屏。</p>',
        '          </div>',
        '          <aside class="hero-card">',
        '            <p class="section-label">Curated observances</p>',
        '            <h2 class="section-title">把节日订阅做成一个安静、长期可用的入口页</h2>',
        '            <p class="section-copy">你可以直接订阅全部，或者按主题拆开：环保与社会议题、文化与阅读、常见节庆。页面保留极简信息架构，但现在把最像工具页的部分压到第二屏，让首屏更像一个被打开的入口。</p>',
        '            <div class="stats">',
        '              <div class="stat"><strong>4</strong><span>个可订阅日历源</span></div>',
        '              <div class="stat"><strong>5 年</strong><span>默认生成窗口</span></div>',
        '              <div class="stat"><strong>0</strong><span>大陆法定节假日重复项</span></div>',
        '            </div>',
        '          </aside>',
        '        </div>',
        '      </section>',
        '      <section class="subscriptions section-fade" id="subscriptions">',
        '        <div class="subscriptions-inner">',
        '          <div class="subscriptions-header">',
        '            <h2>选择你的订阅入口</h2>',
        '            <p>每个日历都可以直接作为 ICS 链接订阅。下面保留原本清晰的信息结构，但换成更适合公开展示的沉浸式卡片布局。</p>',
        '          </div>',
        '          <div class="subscription-grid">',
        *cards,
        '          </div>',
        '        </div>',
        '      </section>',
        '    </main>',
        '    <footer class="footer-note section-fade" id="about">',
        '      <div class="footer-note-inner">',
        '        已明确排除中国大陆法定节假日，适合与现有法定节假日订阅源并行使用。若你的客户端支持订阅远程 ICS 链接，可直接使用以上地址。',
        '      </div>',
        '    </footer>',
        '  </div>',
        '  <script type="module">',
        "    import * as THREE from 'https://unpkg.com/three@0.164.1/build/three.module.js';",
        "",
        "    class HolidayParticleField {",
        "      constructor(canvas) {",
        "        this.canvas = canvas;",
        "        this.prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;",
        "        this.pointer = { x: 0, y: 0 };",
        "        this.enterStage = document.querySelector('.enter-stage-inner');",
        "        this.enterButton = document.querySelector('.enter-button');",
        "        this.fadeSections = [...document.querySelectorAll('.section-fade')];",
        "        this.clock = new THREE.Clock();",
        "        this.scene = new THREE.Scene();",
        "        this.camera = new THREE.PerspectiveCamera(46, window.innerWidth / window.innerHeight, 0.1, 120);",
        "        this.camera.position.set(0, 0.2, 22);",
        "        this.renderer = new THREE.WebGLRenderer({ canvas: this.canvas, antialias: true, alpha: true });",
        "        this.renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2));",
        "        this.renderer.setSize(window.innerWidth, window.innerHeight);",
        "        this.group = new THREE.Group();",
        "        this.scene.add(this.group);",
        "        this.scene.fog = new THREE.FogExp2(0x241b23, 0.025);",
        "",
        "        this.addLights();",
        "        this.createStars();",
        "        this.createConstellation();",
        "        this.createHalo();",
        "        this.handleResize = this.handleResize.bind(this);",
        "        this.handlePointerMove = this.handlePointerMove.bind(this);",
        "        this.handleEnter = this.handleEnter.bind(this);",
        "        this.revealSections = this.revealSections.bind(this);",
        "        window.addEventListener('resize', this.handleResize);",
        "        window.addEventListener('pointermove', this.handlePointerMove, { passive: true });",
        "        window.addEventListener('scroll', this.revealSections, { passive: true });",
        "        this.enterButton?.addEventListener('click', this.handleEnter);",
        "        this.revealSections();",
        "        this.render = this.render.bind(this);",
        "        this.render();",
        "      }",
        "",
        "      addLights() {",
        "        const ambient = new THREE.AmbientLight(0xdccfcc, 1.18);",
        "        const point = new THREE.PointLight(0x6f8f8b, 17, 100, 1.7);",
        "        point.position.set(2.8, 3.0, 13);",
        "        const rim = new THREE.PointLight(0xb8a6b8, 10, 84, 1.2);",
        "        rim.position.set(-5.5, -1.5, 7);",
        "        const moss = new THREE.PointLight(0x4d6b45, 7, 70, 1.1);",
        "        moss.position.set(0, 4, -4);",
        "        this.scene.add(ambient, point, rim, moss);",
        "      }",
        "",
        "      createStars() {",
        "        const count = window.innerWidth < 768 ? 3400 : 5600;",
        "        const positions = new Float32Array(count * 3);",
        "        const colors = new Float32Array(count * 3);",
        "        const sizes = new Float32Array(count);",
        "        const seeds = new Float32Array(count);",
        "        const color = new THREE.Color();",
        "        const palette = [0xcfc6cf, 0xb8a6b8, 0x7c9a74, 0x4d6b45, 0xe7ddd8, 0x6f8f8b];",
        "",
        "        for (let index = 0; index < count; index += 1) {",
        "          const stride = index * 3;",
        "          const radius = 6 + Math.random() * 28;",
        "          const angle = Math.random() * Math.PI * 2;",
        "          const spread = Math.pow(Math.random(), 0.72);",
        "          const height = (Math.random() - 0.5) * 18;",
        "          positions[stride] = Math.cos(angle) * radius * spread + (Math.random() - 0.5) * 1.6;",
        "          positions[stride + 1] = height;",
        "          positions[stride + 2] = (Math.random() - 0.5) * 30;",
        "          color.setHex(palette[Math.floor(Math.random() * palette.length)]);",
        "          color.offsetHSL((Math.random() - 0.5) * 0.03, 0, (Math.random() - 0.5) * 0.08);",
        "          colors[stride] = color.r;",
        "          colors[stride + 1] = color.g;",
        "          colors[stride + 2] = color.b;",
        "          sizes[index] = 0.22 + Math.random() * 0.9;",
        "          seeds[index] = Math.random() * 100;",
        "        }",
        "",
        "        const geometry = new THREE.BufferGeometry();",
        "        geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3));",
        "        geometry.setAttribute('color', new THREE.BufferAttribute(colors, 3));",
        "        geometry.setAttribute('size', new THREE.BufferAttribute(sizes, 1));",
        "        geometry.setAttribute('seed', new THREE.BufferAttribute(seeds, 1));",
        "",
        "        const material = new THREE.ShaderMaterial({",
        "          transparent: true,",
        "          depthWrite: false,",
        "          blending: THREE.AdditiveBlending,",
        "          vertexColors: true,",
        "          uniforms: { pixelRatio: { value: Math.min(window.devicePixelRatio || 1, 2) }, time: { value: 0 } },",
        "          vertexShader: `",
        "            attribute float size;",
        "            attribute float seed;",
        "            varying vec3 vColor;",
        "            uniform float pixelRatio;",
        "            uniform float time;",
        "            void main() {",
        "              vColor = color;",
        "              vec3 transformed = position;",
        "              transformed.x += sin(time * 0.17 + seed) * 0.06;",
        "              transformed.y += sin(time * 0.22 + seed * 1.7) * 0.12;",
        "              transformed.z += cos(time * 0.12 + seed * 0.8) * 0.24;",
        "              vec4 mvPosition = modelViewMatrix * vec4(transformed, 1.0);",
        "              float twinkle = 0.75 + 0.25 * sin(time * 1.8 + seed * 8.0);",
        "              gl_PointSize = size * twinkle * (220.0 / -mvPosition.z) * pixelRatio;",
        "              gl_Position = projectionMatrix * mvPosition;",
        "            }`,",
        "          fragmentShader: `",
        "            varying vec3 vColor;",
        "            void main() {",
        "              float distanceToCenter = length(gl_PointCoord - vec2(0.5));",
        "              float strength = smoothstep(0.52, 0.0, distanceToCenter);",
        "              strength *= 0.72 + 0.28 * smoothstep(0.18, 0.0, distanceToCenter);",
        "              gl_FragColor = vec4(vColor, strength * 0.82);",
        "            }`,",
        "        });",
        "",
        "        this.starField = new THREE.Points(geometry, material);",
        "        this.group.add(this.starField);",
        "      }",
        "",
        "      createConstellation() {",
        "        const geometry = new THREE.BufferGeometry();",
        "        const positions = new Float32Array([",
        "          -6.4,  1.9,  1.8,   -3.0,  0.7, -0.9,",
        "          -3.0,  0.7, -0.9,   -0.5,  2.8, -2.2,",
        "          -0.5,  2.8, -2.2,    2.6,  0.6, -0.7,",
        "           2.6,  0.6, -0.7,    5.7, -1.2,  1.4,",
        "          -1.3, -1.7,  0.4,    1.8, -3.0, -1.8,",
        "        ]);",
        "        geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3));",
        "        const material = new THREE.LineBasicMaterial({ color: 0xcfc6cf, transparent: true, opacity: 0.16 });",
        "        this.constellation = new THREE.LineSegments(geometry, material);",
        "        this.scene.add(this.constellation);",
        "",
        "        const nodeGeometry = new THREE.SphereGeometry(0.06, 14, 14);",
        "        const nodeMaterial = new THREE.MeshBasicMaterial({ color: 0xe7ddd8, transparent: true, opacity: 0.82 });",
        "        const nodes = [",
        "          [-6.4, 1.9, 1.8], [-3.0, 0.7, -0.9], [-0.5, 2.8, -2.2], [2.6, 0.6, -0.7], [5.7, -1.2, 1.4], [-1.3, -1.7, 0.4], [1.8, -3.0, -1.8],",
        "        ];",
        "        nodes.forEach(([x, y, z]) => {",
        "          const mesh = new THREE.Mesh(nodeGeometry, nodeMaterial);",
        "          mesh.position.set(x, y, z);",
        "          this.scene.add(mesh);",
        "        });",
        "",
        "        const archCurve = new THREE.EllipseCurve(0, -0.3, 6.8, 5.6, Math.PI * 1.02, Math.PI * 1.98, false, 0);",
        "        const archPoints = archCurve.getPoints(120).map((point) => new THREE.Vector3(point.x, point.y, -3.6));",
        "        const archGeometry = new THREE.BufferGeometry().setFromPoints(archPoints);",
        "        const archMaterial = new THREE.LineBasicMaterial({ color: 0x7c9a74, transparent: true, opacity: 0.14 });",
        "        this.archway = new THREE.Line(archGeometry, archMaterial);",
        "        this.scene.add(this.archway);",
        "      }",
        "",
        "      createHalo() {",
        "        const haloGeometry = new THREE.TorusGeometry(7.3, 0.04, 16, 180);",
        "        const haloMaterial = new THREE.MeshBasicMaterial({ color: 0x6f8f8b, transparent: true, opacity: 0.13 });",
        "        this.halo = new THREE.Mesh(haloGeometry, haloMaterial);",
        "        this.halo.rotation.x = Math.PI / 2.4;",
        "        this.halo.rotation.y = Math.PI / 10;",
        "        this.scene.add(this.halo);",
        "      }",
        "",
        "      handleResize() {",
        "        this.camera.aspect = window.innerWidth / window.innerHeight;",
        "        this.camera.updateProjectionMatrix();",
        "        this.renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2));",
        "        this.renderer.setSize(window.innerWidth, window.innerHeight);",
        "        if (this.starField?.material?.uniforms?.pixelRatio) {",
        "          this.starField.material.uniforms.pixelRatio.value = Math.min(window.devicePixelRatio || 1, 2);",
        "        }",
        "      }",
        "",
        "      handlePointerMove(event) {",
        "        this.pointer.x = (event.clientX / window.innerWidth) * 2 - 1;",
        "        this.pointer.y = -((event.clientY / window.innerHeight) * 2 - 1);",
        "        if (this.enterStage && !this.prefersReducedMotion) {",
        "          this.enterStage.style.transform = `translate3d(${this.pointer.x * 12}px, ${this.pointer.y * 8}px, 0)`;",
        "        }",
        "      }",
        "",
        "      handleEnter(event) {",
        "        event.preventDefault();",
        "        const target = document.querySelector(this.enterButton.getAttribute('href'));",
        "        this.enterStage?.animate([",
        "          { opacity: 1, transform: this.enterStage.style.transform || 'translate3d(0,0,0) scale(1)' },",
        "          { opacity: 0.16, transform: 'translate3d(0, -18px, 0) scale(0.985)' },",
        "        ], { duration: 900, easing: 'cubic-bezier(0.22, 1, 0.36, 1)', fill: 'forwards' });",
        "        target?.scrollIntoView({ behavior: 'smooth', block: 'start' });",
        "        setTimeout(() => this.revealSections(), 240);",
        "      }",
        "",
        "      revealSections() {",
        "        const trigger = window.innerHeight * 0.88;",
        "        this.fadeSections.forEach((section) => {",
        "          const rect = section.getBoundingClientRect();",
        "          if (rect.top < trigger) section.classList.add('is-visible');",
        "        });",
        "      }",
        "",
        "      render() {",
        "        const elapsed = this.clock.getElapsedTime();",
        "        const motion = this.prefersReducedMotion ? 0.18 : 1;",
        "        if (this.starField?.material?.uniforms?.time) {",
        "          this.starField.material.uniforms.time.value = elapsed;",
        "        }",
        "        this.group.rotation.y = elapsed * 0.02 * motion + this.pointer.x * 0.06;",
        "        this.group.rotation.x = Math.sin(elapsed * 0.11) * 0.04 * motion + this.pointer.y * 0.035;",
        "        this.group.position.x = this.pointer.x * 0.42;",
        "        this.group.position.y = this.pointer.y * 0.24;",
        "        this.group.position.z = Math.sin(elapsed * 0.18) * 0.45 * motion;",
        "        this.constellation.rotation.z = elapsed * 0.02 * motion;",
        "        this.constellation.rotation.y = elapsed * 0.045 * motion;",
        "        this.halo.rotation.z = elapsed * 0.05 * motion;",
        "        this.halo.rotation.y = Math.PI / 10 + Math.sin(elapsed * 0.24) * 0.09 * motion;",
        "        if (this.archway) {",
        "          this.archway.rotation.z = Math.sin(elapsed * 0.12) * 0.025 * motion;",
        "          this.archway.position.y = Math.sin(elapsed * 0.2) * 0.16 * motion;",
        "        }",
        "        this.camera.position.z = 22 - Math.sin(elapsed * 0.16) * 0.45 * motion;",
        "        this.renderer.render(this.scene, this.camera);",
        "        if (!this.prefersReducedMotion) {",
        "          requestAnimationFrame(this.render);",
        "        }",
        "      }",
        "    }",
        "",
        "    new HolidayParticleField(document.getElementById('three-scene'));",
        "  </script>",
        "</body>",
        "</html>",
    ]
    return "\n".join(lines) + "\n"


def build_all_calendars(
    holidays: Iterable[dict],
    start_year: int,
    years: int,
    domain: str,
    dist_dir: str | Path,
    base_url: str | None = None,
) -> dict[str, str]:
    calendar_events = {filename: [] for filename in CALENDAR_METADATA}
    dtstamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")

    for holiday in holidays:
        if not holiday.get("enabled", False):
            continue
        for year in range(start_year, start_year + years):
            event = expand_holiday(holiday, year, domain)
            calendar_events["all.ics"].append(event)
            calendar_events[CATEGORY_TO_FILE[event["category"]]].append(event)

    dist_path = Path(dist_dir)
    dist_path.mkdir(parents=True, exist_ok=True)
    outputs: dict[str, str] = {}
    for filename, events in calendar_events.items():
        target = dist_path / filename
        target.write_text(render_calendar(filename, events, dtstamp), encoding="utf-8")
        outputs[filename] = str(target)
    if base_url:
        index_target = dist_path / "index.html"
        index_target.write_text(render_index(base_url), encoding="utf-8")
        outputs["index.html"] = str(index_target)
    return outputs


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build holiday ICS subscription files.")
    parser.add_argument("--start-year", type=int, default=date.today().year)
    parser.add_argument("--years", type=int, default=DEFAULT_YEARS)
    parser.add_argument("--domain", default=CALENDAR_DOMAIN)
    parser.add_argument("--base-url", default=None)
    parser.add_argument("--dist-dir", default=str(DIST_DIR))
    parser.add_argument("--data-file", default=str(DATA_FILE))
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    holidays = load_holidays(args.data_file)
    validate_holidays(holidays)
    outputs = build_all_calendars(
        holidays=holidays,
        start_year=args.start_year,
        years=args.years,
        domain=args.domain,
        dist_dir=args.dist_dir,
        base_url=args.base_url,
    )
    print(f"Generated {len(outputs)} calendar files in {args.dist_dir}.")
    for filename in sorted(outputs):
        print(f"- {filename}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
